apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  labels:
    app: auth-service
type: Opaque
data:
  MONGODB_URI: {{ .Values.env.mongo.uri | b64enc | quote}}
  JWT_SECRET: {{ .Values.env.jwt.secret | b64enc | quote }}
  JWT_REFRESH_SECRET: {{ .Values.env.jwt.refreshSecret | b64enc | quote }}
  JWT_ACCESS_EXPIRE: {{ .Values.env.jwt.accessExpire | b64enc | quote }}
  JWT_REFRESH_EXPIRE: {{ .Values.env.jwt.refreshExpire | b64enc | quote }}
