apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-config"
  labels:
    app: worker-service
    chart: {{ .Chart.Name }}
data:
  NODE_ENV: "{{ .Values.env.nodeEnv }}"
  LOG_LEVEL: "info"
  MAX_FILE_SIZE: "104857600"
  AUTH_SERVICE_URL: "{{ .Values.env.authServiceUrl }}"