apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-secret"
  labels:
    app: worker-service
    chart: {{ .Chart.Name }}
type: Opaque
data:
  MONGODB_URI: {{ .Values.env.mongo.uri | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.env.redis.password | b64enc | quote }}
  REDIS_HOST: {{ .Values.env.redis.host | b64enc | quote }}
  REDIS_PORT: {{ .Values.env.redis.port | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.env.aws.accessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.env.aws.secretAccessKey | b64enc | quote }}
  AWS_REGION: {{ .Values.env.aws.region | b64enc | quote }}
  AWS_S3_BUCKET: {{ .Values.env.aws.s3Bucket | b64enc | quote }}