apiVersion: v1
kind: Secret
metadata:
  name: app-service-secret
  labels:
    app: app-service
type: Opaque
data:
  MONGODB_URI: {{ .Values.secrets.mongo.uri | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redis.password | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.aws.accessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.aws.secretAccessKey | b64enc | quote }}
  AWS_REGION: {{ .Values.secrets.aws.region | b64enc | quote }}
  AWS_S3_BUCKET: {{ .Values.secrets.aws.s3Bucket | b64enc | quote }}