apiVersion: v2
name: image-optimiser
description: Complete microservices image optimiser system
type: application
version: 0.2.0
appVersion: 1.0.0

dependencies:
  - name: mongodb
    version: "15.6.0"
    repository: https://charts.bitnami.com/bitnami

  - name: redis
    version: "19.1.3"
    repository: https://charts.bitnami.com/bitnami
    
  - name: gateway-service
    version: "0.1.0"
    repository: "file://./gateway-service"
  
  - name: auth-service
    version: "0.1.0"
    repository: "file://./auth-service"
  
  - name: app-service
    version: "0.1.0"
    repository: "file://./app-service"
