secrets:
  mongo:
    uri: "mongodb://user:password@mongodb/image"

  redis:
    password: "change-me-secure-password"

  aws:
    region: "ap-south-1"
    s3Bucket: 
    accessKeyId: ""
    secretAccessKey: ""
